# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_event_eventcategory_usercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='profileId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rollNumber',
            field=models.IntegerField(),
        ),
    ]
