# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171006_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rollNumber',
            field=models.CharField(max_length=200),
        ),
    ]
