# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20171007_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseUser',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('profileId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=200)),
                ('userType', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseUser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
