# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171008_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=6)),
                ('department', models.CharField(max_length=50)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseUser')),
            ],
        ),
    ]
