# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='publisherSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('contentType', models.CharField(max_length=100)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseUser')),
            ],
        ),
    ]
