# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_publishersettings_contactnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='publisher_id',
        ),
        migrations.AddField(
            model_name='event',
            name='profileId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.baseUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
