# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20171012_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='Url',
        ),
    ]
