# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20171012_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Url',
            new_name='url',
        ),
    ]
