# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20171012_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryId',
            field=models.CharField(default='', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default='1999-05-31 12:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='1999-05-31 12:00'),
        ),
    ]
