# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:50
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20171012_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.CharField(default=builtins.id, max_length=2, primary_key=True, serialize=False),
        ),
    ]
