# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20171012_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
