# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20171012_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='categoryId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.Category'),
        ),
    ]
