# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20171012_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
