# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20171012_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='categoryId',
            field=models.CharField(max_length=100),
        ),
    ]
