# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20171012_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryId',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.CharField(default='', max_length=2, primary_key=True, serialize=False),
        ),
    ]
