# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20171012_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='profileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.baseUser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
