# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20171014_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='googleCode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default='2017-10-31 12:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default='2017-10-31 12:00'),
        ),
    ]
