# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20171026_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='googleCode',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
